CheatSheets/git-cheatsheet.md

> Add `git checkout` variant
> Added new command which is commonly used to create and switch to a new branch

Add 'git checkout' command variant

---

CheatSheets/git-cheatsheet.md

git contribuition

---

CheatSheets/git-cheatsheet.md

> Add content 
> Added git add . command to add all unstaged changes at once.

Added git add . cammand to add all unstaged changes at once

---

CheatSheets/git-cheatsheet.md

git_commands_added

---

CheatSheets/git-cheatsheet.md
CheatSheets/npm-cheatsheet.md

Updates git-cheatsheet and included the `git fetch` cmd
Updates npm-cheatsheet and includes commands to `run tests` and `run scripts`

update: add git and npm cheatsheets

---

CheatSheets/markdown-cheatsheet.md

> added markdown syntax in markdown-cheatsheet.md. Issue: #7 
- [ x] Used an informative name for this pull request.

added markdown syntax in markdown-cheatsheet.md

---

CheatSheets/npm-cheatsheet.md

> Add ``` npm update -g ``` command
> Add npm command used for updating individual packages

Add command to update individual npm packages

---

CheatSheets/npm-cheatsheet.md

>  Add new CheatSheet
> I have added a cheatsheet for the npm section

added cheatsheet in node cheatsheet

---

CheatSheets/npm-cheatsheet.md

Added Some NPM Commands in Npm cheatsheet

---

CheatSheets/git-cheatsheet.md

Added some git commands in git cheatsheets

---

CheatSheets/npm-cheatsheet.md

> Added new npm commands 
> Added to 2 new npm commands to the npm cheatsheet

added 2 new npm commands

---

CheatSheets/npm-cheatsheet.md

> I added **npm un** to our cheat sheet. Can I also add nvm commands to this sheet?
> I found your repo on Hacktoberfest Discord and thought it was an awesome project! 😎👍

Hacktoberfest 2022 - Updated NPM cheat sheet

---

CheatSheets/nvm-cheatsheet.md

LGTM! ✌️
> Added new cheat sheet!
> Hey it’s me once again! I decided to take some more effort and decided that this could come in handy for every Node.JS developer having issues with version management!

Hacktoberfest 2022 - Added my Node Version Manager cheat sheet

---

CheatSheets/nvm-cheatsheet.md

Running commands in a specific version and setting colors, LGTM ✌️
> Added a few new commands to our cheat sheet

Hacktoberfest 2022 - Added new things to the NVM Cheat sheet

---

CheatSheets/windows-cheatsheet.md
README.md

> `Add new CheatSheet`
> Add `windows-cheatsheet.md` file for `Windows Keyboard Shortcuts`

Add windows-cheatsheet.md file for Windows Keyboard Shortcuts - resolve issue #33

---

CheatSheets/vscode-cheatsheet.md
README.md

> `Add new CheatSheet`
> Add `vscode-cheatsheet.md` file
> Add `vscode-cheatsheet.md` file for `VSCode Keyboard Shortcuts` - `resolve or fixes issue no #35`

Add vscode-cheatsheet.md file for VSCode Keyboard Shortcuts - resolve or fixes issue no #35

---

CheatSheets/chrome-devtools-cheatsheet.md
README.md

> `Add new CheatSheet`
> Add a `chrome-devtools-cheatsheet.md` file.
> Add a chrome-devtools-cheatsheet.md file for Chrome DevTools Keyboard Shortcuts - resolved issue no #37

Add a chrome-devtools-cheatsheet.md file for Chrome DevTools Keyboard Shortcuts - resolved issue no #37

---

CheatSheets/git-cheatsheet.md

> Add new CheatSheet 
> Temporarily store modified, tracked files in order to change branches

adding cheatsheets of TEMPORARY COMMITS

---

CheatSheets/git-cheatsheet.md
CheatSheets/windows-cheatsheet.md

Added command for task manager

---

CheatSheets/windows-cheatsheet.md

added new commands for windows File explorer
https://github.com/crescentpartha/CheatSheets-for-Developers/issues/41

updated the windows.md

---

CheatSheets/vscode-cheatsheet.md

> Add contents
> Added more shortcuts in :
1. Basic Editing
2. Multi-cursor and Selection
3. Editor Management
4. File Management
[Multiple Cursor](https://developercommunity.visualstudio.com/t/add-add-cursor-below-and-add-cursor-above-keyboard/1172372)
[Open Recently Closed Editor](https://marketplace.visualstudio.com/items?itemName=major.VSDocumentReopen)

Added contents in VScode Cheat Sheet

---

CheatSheets/yarn-cheatsheet.md
README.md

> Add new CheatSheet 
> Adding valid commands for using the Yarn package manager

Added commands for Yarn

---

CheatSheets/git-cheatsheet.md

> Adding new Logs commands in Inspection & Comparison

Adding cheatsheets of Inspection & Comparison

---

CheatSheets/npm-cheatsheet.md

Chore: added more npm cheat sheet

---

CheatSheets/vscode-cheatsheet.md

> Add content(s) |
> Added more Vscode cheatsheet

Chore: added more vscode cheatsheet

---

CheatSheets/Python-cheatsheet.md

> Adding more content to Python CheatSheet

Python cheatsheet update1

---

CheatSheets/windows-cheatsheet.md

> added more content to windows cheatsheet
> 
> 

updated windows cheatsheet

---

CheatSheets/vscode-cheatsheet.md

> Added more content to vs-code cheatsheet

chore: updated vscode cheatsheet

---

CheatSheets/Python-cheatsheet.md

Python Cheatsheet update2

---

README.md

Added css-cheatsheet to the README.md file

---

CheatSheets/vscode-cheatsheet.md

Added Shift + Alt + up/down command to vscode-CheatSheets

Added Shift + Alt + up/down command to vscode-CheatSheets

---

CheatSheets/markdown-cheatsheet.md

Added Extended markdown syntax
> Add content to markdown-cheatsheet.md
> Added Extended markdown syntax to the markdown-cheatsheet.md in tabluar form 

Added Extended Markdown Syntax

---

CheatSheets/git-cheatsheet.md

> Add content(s) |  Add new CheatSheet | 
Added more Git CheatSheet for Developers

 Chore: Added more Git CheatSheet for Developers

---

CheatSheets/git-cheatsheet.md

Added a new command in Inspection and comparison section of git cheatsheet.
**Please accept for hacktoberfest 2022**

Added new command in git cheatsheet

---

CheatSheets/Python-cheatsheet.md

Python cheatsheet update 3

---

CheatSheets/Python-cheatsheet.md

Add contents
Explained the list.append and list.extend methods

Added Explanation to Methods

---

CheatSheets/css-cheatsheet.md

Add contents to CSS Cheatsheet
General improvements on CSS cheatsheet. 
Improvements on file structure and add some more CSS tips.
Related to #82 

Improvements on css cheatsheet

---

CheatSheets/vscode-cheatsheet.md

Added a new shortcut for vscode that lets you select blocks of text.

---

CheatSheets/windows-cheatsheet.md

> added a few more alt and windows button shortcuts in the file

added more shortcuts in worksheet-cheatsheet.md file

---

CheatSheets/git-cheatsheet.md

> Adding and reordering git Inspection & Comparison commands

Git cheatsheets

---

CheatSheets/git-cheatsheet.md

> Add new CheatSheet 
> Adding more configuration commands in Git Configuration

Adding cheatsheets of Git Configuration

---

CheatSheets/html-cheatsheet.md
CheatSheets/vscode-cheatsheet.md

Add command to delete line (vscode)

---

CheatSheets/windows-cheatsheet.md

These are the default shortcuts

Added Windows 11 Touchpad shortcuts

---

.github/workflows/welcome.yml

> This action will welcome new users

added welcome workflow

---

CheatSheets/Python-cheatsheet.md

Python cheatsheet update 4

---

CheatSheets/windows-cheatsheet.md

Add content(s)
added `win + D` shortcut in windows cheatsheet

add win+d shortcut

---

CheatSheets/linux-cheatsheet.md
README.md

> Adds linux-cheatsheet.md and adds a link to it in the README.md
> Based on [Add cheatsheet for Linux command line. #96 ](https://github.com/crescentpartha/CheatSheets-for-Developers/issues/96)
> Here is the linux cheat sheet. Obviously not every command can be covered so i tried to pick just the most useful and most used commands.

Added cheatsheet for Linux command line.

---

CheatSheets/Python-cheatsheet.md

Python Cheatsheet update 5

---

CheatSheets/git-cheatsheet.md

Add contents
Added the `git rm --cached <file>` and `git checkout` <file> commands

Updated git-cheatsheet.md

---

CheatSheets/html-cheatsheet.md

Adding the <em> tag on the html-cheatsheet file

---

README.md
docs/CONTRIBUTING.md

Made some minor tweaks to the grammar and overall text formatting in the files, including adding possible missing punctuations and the like, wherever necessary.

Made some minors tweaks to the grammar and overall text formatting.

---

CheatSheets/java-cheatsheet.md
README.md

Add new CheatSheet for Java developers.
Thank You

Added java-cheatsheet.md

---

README.md

Fixed some mistakes in line 2. @crescentpartha Please review.
> Correct documentation
- [ x] Search for duplicates.
- [ x] Used an informative name for this pull request.

Docs(Update): Fixed errors

---

CheatSheets/git-cheatsheet.md

> Adding cheatsheets of Rewrite History in git-cheatsheets

Adding cheatsheets of Rewrite History

---

CheatSheets/windows-cheatsheet.md

> Add content(s) | Add new feature 
> In this PR, I have added some new shortcuts for windows users.
> If applicable, add `screenshots or a modified `UI link` to help understand your contribution.
> Also, I made one PR before this and asked to make some changes. As I'm new to open source and didn't know much about how to update the previous PR, that's why I have created the new PR.

Now I have updated the changes and added some windows keyboard shortcuts.

---

CheatSheets/conda-cheatsheet.md
README.md

> Add content(s) | Add new CheatSheet
> Adding a cheatsheet for conda managing

Added conda cheatsheet

---

CheatSheets/Python-cheatsheet.md

> Added more content to Python Cheatsheet

Python Cheatsheet update 6

---

CheatSheets/windows-cheatsheet.md

> Address this issue https://github.com/crescentpartha/CheatSheets-for-Developers/issues/122
> Added the shortcut to use windows snipping tool to take a snip of screen

Added windows snipping tool shortcut to windows-cheatsheet.md file

---

CheatSheets/cpp-stl-cheetsheet.md

> Add content(s) : cpp-stl-cheetsheet.md
> Complete C++ STL which include vector, set, unordered set, map, stack, queue, deque, and vector pair.
> Link : https://github.com/khushpreet-007/CheatSheets-for-Developers/blob/main/CheatSheets/cpp-stl-cheetsheet.md
>  Created cpp-stl-cheetsheet.md
- [] Read our [contributing guidelines](../docs/CONTRIBUTING.md).

Created cpp-stl-cheetsheet.md

---

CheatSheets/html-cheatsheet.md

> Add content(s) | Add new CheatSheet | Add new feature
> Added new HTML commands which are valid in HTML5 and some in CSS
> Wanted to add more but format gets disturbed. You could help me to add few more.

Few commands added

---

CheatSheets/java-cheatsheet.md

added types of variables in java

---

CheatSheets/git-cheatsheet.md

> Adding and reordering git Branching & Merging commands

Adding cheatsheets of Branching & Merging

---

CheatSheets/Python-cheatsheet.md

> Added more content to Cheatsheet

Python Cheatsheet update 7

---

CheatSheets/windows-cheatsheet.md

Added shortcuts of mark mode too

Added Command Prompt shortcuts

---

CheatSheets/windows-cheatsheet.md

> Add keyboard shortcut to open snipping tool in windows-cheatsheet.md file
> Easier way to save a screenshot of just a selected area from your screen.

Added Shortcut to take Screenshot of Selected Area

---

CheatSheets/docker-cheatsheet.md
README.md

> Add new CheatSheet for docker
> Added docket cheatsheet

added docker cheatsheet

---

CheatSheets/php-cheatsheet.md

created php cheatsheet

---

CheatSheets/Python-cheatsheet.md

> One comment about Fstrings named
- [X ] Used an informative name for this pull request.

One more comment about Fstrings

---

CheatSheets/Python-cheatsheet.md

python Cheatsheet update 8

---

CheatSheets/Python-cheatsheet.md

> this is my Final and last commit for python cheatsheet update and now the cheatsheet is complete

Final and last python cheatsheet update

---

CheatSheets/css-cheatsheet.md

Modification in CSS Style properties
Removing the properties which are not present in the CSS
Adding values that can be set to the property.
Changes in description to make it more clear to the developer.
NA

Modification in CSS Style properties (adding values, making description more clear, removing fake properties)

---

CheatSheets/bash_cheatsheet.md

> Add  
> added bash cheatsheet under cheatsheet section

Added bash_cheatsheet.md file

---

CheatSheets/conda-cheatsheet.md

Added Some Command in Conda cheatsheet

---

CheatSheets/windows-cheatsheet.md

Updated Windows+R and Windows+M Command
> In this PR I upgraded some basic command that will help user.
> I Added Windows+R that will shop run dailog box 
and Second I added Windows+M for minimizing all running App.

Updated Windows Commands in Windows CheatSheet

---

CheatSheets/java-cheatsheet.md

added about collection framework in Java #139 
added about collections like set, list, queue, stack, deque, map.

Java cheatsheet update (Added collections framework)

---

CheatSheets/html-cheatsheet.md

> Added HTML5 input tag attributes in html cheatSheet.

added HTML5 input tag attributes in html cheatsheet

---

CheatSheets/cpp-stl-cheatsheet.md

> Added List and Priority Queue and Added brief information of each container
> Please add the changes to Hacktober Fest
- [x ] Search for duplicates.
- [ x] Used an informative name for this pull request.
- 

Updated cpp-stl-cheatsheet.md 

---

CheatSheets/linux-cheatsheet.md

> Added
Archives(Tar Files)
Disk Usage
Search
> Can this PR be labelled for hacktoberfest ?
- [x ] Search for duplicates.
- [x ] Used an informative name for this pull request.

Linux commands added in CheatSheet

---

CheatSheets/angular-cheatsheet.md

> Added AngularJS Cheatsheet
> NONE
> NONE

Added AngularJS Cheatsheet 

---

CheatSheets/git-cheatsheet.md

> Essential command added to git-cheatsheet.md
> Adding command for merging unrelated histories from the remote branch this issue occurs often while dealing with remote branches and accepting pulls from remote.

Update git-cheatsheet.md with unrealted histories command 

---

CheatSheets/npx-cheetsheet.md
README.md

> Added npx cheatsheet for beginners
> NPX is a very handy replacement of npm for initiating react projects so, I have added npx cheatsheet.

Added NPX Cheatsheet

---

CheatSheets/linux-cheatsheet.md

> Added commands to the linux-cheatsheet.md
> Added some shell shortcuts and basic ,usefull commands

added more commands to the linux cheatsheet

---

CheatSheets/JavaScript-CheatSheet.md

> Add contents
> Add 3 array methods in javascript cheatsheet

add 3 array methods in javascript cheatsheet

---

CheatSheets/linux-cheatsheet.md

> I Added Some file handle command for linux cheatsheet 
> I Added Commands like Display 10 lines of code and Encrypt and decrypt file and show numbers and lines in file.

Updated Some Linux file command in linux cheatsheet

---

CheatSheets/cpp-stl-cheatsheet.md

> Added sorting by first and second element in cpp pair
>Uses internal quicksort implementation for sorting

Update cpp-stl-cheatsheet.md with pair sorting 

---

CheatSheets/git-cheatsheet.md

Added few git commands to git-cheatsheet

---

CheatSheets/git-cheatsheet.md

Added Some commands in git cheatsheet

---

CheatSheets/git-cheatsheet.md

> Add git commands per issue #80 (help, grep, bugreport, and restore) to [git-cheatsheet.md](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/CheatSheets/git-cheatsheet.md)

feat: add git commands #80

---

CheatSheets/php-cheatsheet.md

> Update php cheatsheet
> I am going through the php cheatsheets and i found that the previous contributor didnt add anything and it dont have any relevant with php cheatsheets without important terminologies so i have added it

Update php cheatsheet

---

CheatSheets/cmd-cheatsheet.md

"Bug fix"
Fixed a typo in a command

Fix typo in cmd-cheatsheet.md

---

CheatSheets/docker-cheatsheet.md

Add command on how to remove all unused Docker related items.
By executing the added command, one can remove everything that is not mailed down and currently in use

Update Docker Cheatsheet with docker system command

---

CheatSheets/java-cheatsheet.md

> Added topics and subtopics : encapsulation (java packages), abstraction (abstract class, interface) and polymorphism (method overloading and overriding) to Java cheat sheet.
This PR resolves issue #192 
Please approve under hacktoberfest label, thank you.

Added encapsulation, abstraction, polymorphism to Java cheatsheet

---

CheatSheets/Python-cheatsheet.md

> Add content(s) | Added the shortcut to comment and uncomment the selected code
> Added the shortcut to comment and uncomment the selected code

Added the shortcut to comment and uncomment the selected code

---

CheatSheets/vscode-cheatsheet.md

Added some more shortcuts

---

CheatSheets/regex-cheatsheet.md
README.md

Added REGEX Cheatsheet and Updated README file 

---

CheatSheets/terraform-cheatsheet.md

> Add new CheatSheet 
> Terraform is an infrastructure as code tool that lets you build, change, and version cloud and on-prem resources safely and efficiently.n

Add terraform cheatsheet

---

CheatSheets/mongodb-cheatsheet.md

mongo_db_cheatsheet_updated

---

CheatSheets/html-cheatsheet.md

>address this issue https://github.com/crescentpartha/CheatSheets-for-Developers/issues/90
> added form elements, updated forms and media

added form elements, updated forms and media

---

README.md

> Sort giant list of cheat sheets into collapsing categories
> This PR will making finding specific cheat sheets or just browsing them easier.
> Based on [Issue #230](https://github.com/crescentpartha/CheatSheets-for-Developers/issues/230)
> I'm not experienced with every tool/language in this repo so checking if I categorized it correctly would be greatly appreciated! 

Sort giant list into collapsing categories

---

CheatSheets/configure-react-cheatsheet.md
CheatSheets/npx-cheetsheet.md

Added the `npx configure-react` commands that help setup react app faster
Added the npx configure-react commands that help setup react app faster
https://www.npmjs.com/package/configure-react
This help any new developer to set the React App Faster and can start learning and implementing things easily

Added the npx configure-react commands that help setup react app faster

---

CheatSheets/nodeJs-cheatsheet.md

I have updated the node js cheatsheets

updated nodeJs-cheatsheet

---

CheatSheets/chrome-devtools-cheatsheet.md

chrome-dev-tools cheatsheet added

---

CheatSheets/linux-cheatsheet.md

> Added some linux commands
> added new section of environment variables

added linux commands to the cheatsheet

---

CheatSheets/cmd-cheatsheet.md

> Add more important cmd commands and it'll be helpful to all cmd users.
> Not applicable. Because there is nothing about Screenshots or any Links.

Updated cmd Commands list
